version: 2
updates:
- package-ecosystem: nuget
  directory: "/FeatureFlags/FeatureFlags.FunctionalTests"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
    - "samsmithnz"
- package-ecosystem: nuget
  directory: "/FeatureFlags/FeatureFlags.Tests"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
    - "samsmithnz"
- package-ecosystem: nuget
  directory: "/FeatureFlags/FeatureFlags.Web"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
    - "samsmithnz"
- package-ecosystem: nuget
  directory: "/FeatureFlags/FeatureFlags.Models"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
    - "samsmithnz"
- package-ecosystem: nuget
  directory: "/FeatureFlags/FeatureFlags.Service"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
    - "samsmithnz"
