version: 2
updates:
- package-ecosystem: nuget
  directory: "/src/FeatureFlags.FunctionalTests"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
    - "samsmithnz"
  groups:
    functionalTests:
      patterns: ["*"]
      update-types: ["minor", "patch"]
- package-ecosystem: nuget
  directory: "/src/FeatureFlags.Tests"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
    - "samsmithnz"
  groups:
    tests:
      patterns: ["*"]
      update-types: ["minor", "patch"]
- package-ecosystem: nuget
  directory: "/src/FeatureFlags.Web"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
    - "samsmithnz"
  groups:
    web:
      patterns: ["*"]
      update-types: ["minor", "patch"]
- package-ecosystem: nuget
  directory: "/src/FeatureFlags.Models"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
    - "samsmithnz"
  groups:
    models:
      patterns: ["*"]
      update-types: ["minor", "patch"]
- package-ecosystem: nuget
  directory: "/src/FeatureFlags.Service"
  schedule:
    interval: daily
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
    - "samsmithnz"
  groups:
    service:
      patterns: ["*"]
      update-types: ["minor", "patch"]
# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
    time: "06:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  assignees:
  - "samsmithnz"
  groups:
    actions:
      patterns: ["*"]
      update-types: ["minor", "patch"]
