name: "Feature Flags CI/CD"

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    # checkout the repo
    - uses: actions/checkout@v1

    # install dependencies, build, and test
    - name: Setup Dotnet for use with actions
      uses: actions/setup-dotnet@v1.0.0
    - name: Build application version number
      run: |
        Write-Host "Generating Build Number"
        #Get the version from the csproj file
        $xml = [Xml] (Get-Content FeatureFlags/FeatureFlags.Web/FeatureFlags.Web.csproj)
        $initialVersion = [Version] $xml.Project.PropertyGroup.Version
        Write-Host "Initial Version: " $version
        $spliteVersion = $initialVersion -Split "\."
        #Get the build number (number of days since January 1, 2000)
        $baseDate = [datetime]"01/01/2000"
        $currentDate = $(Get-Date)
        $interval = (NEW-TIMESPAN -Start $baseDate -End $currentDate)
        $buildNumber = $interval.Days
        #Get the revision number (number seconds (divided by two) into the day on which the compilation was performed)
        $StartDate=[datetime]::Today
        $EndDate=(GET-DATE)
        $revisionNumber = [math]::Round((New-TimeSpan -Start $StartDate -End $EndDate).TotalSeconds / 2,0)
        #Final version number
        $finalBuildVersion = "$($spliteVersion[0]).$($spliteVersion[1]).$($buildNumber).$($revisionNumber)"
        Write-Host "Major.Minor,Build,Revision"
        Write-Host "Final build number: " $finalBuildVersion
        #Writing final version number back to Azure DevOps variable
        Write-Host "##vso[task.setvariable variable=buildNumber]$finalBuildVersion"
      shell: powershell
    - name: Build with dotnet
      run: dotnet build FeatureFlags/FeatureFlags.Service/FeatureFlags.Service.csproj --configuration Release      
    - name: Automated Tests
      run: dotnet test FeatureFlags/FeatureFlags.Tests/FeatureFlags.Tests.csproj --configuration Release --logger trx --collect "Code coverage" --settings:./FeatureFlags/FeatureFlags.Tests/CodeCoverage.runsettings
    - name: Publish Web Service
      run: dotnet publish FeatureFlags/FeatureFlags.Service/FeatureFlags.Service.csproj --configuration Release 
    - name: Publish Web Site
      run: dotnet publish FeatureFlags/FeatureFlags.Web/FeatureFlags.Web.csproj --configuration Release 
    - name: publish build artifacts back to GitHub
      uses: actions/upload-artifact@master
      with:
        name: serviceapp
        path: FeatureFlags/FeatureFlags.Service/bin/Release/netcoreapp3.0/publish
    - name: publish build artifacts back to GitHub
      uses: actions/upload-artifact@master
      with:
        name: webapp
        path: FeatureFlags/FeatureFlags.Web/bin/Release/netcoreapp3.0/publish

  deploy:
    runs-on: windows-latest
    
    steps:  
    #Login with the secret SP details
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP }}  
    - name: Deployment
      run: |
        Write-Host "Starting deployment"
        Write-Host "Continuing deployment"
      shell: powershell
