name: test action
on: [push]

env:
  buildConfiguration: Release
jobs:
  Build:
    name: Build job
    runs-on: ubuntu-latest
    env:
      myJobVariable: data
    steps:
    - uses: actions/checkout@v1
    - name: dotnet build $myJobVariable
      run: dotnet build FeatureFlags/FeatureFlags.Web/FeatureFlags.Web.csproj --configuration $buildConfiguration
